/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_titikaka_mediaproxyandroid_NDKGateWay */

#ifndef _Included_com_titikaka_mediaproxyandroid_NDKGateWay
#define _Included_com_titikaka_mediaproxyandroid_NDKGateWay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_titikaka_mediaproxyandroid_NDKGateWay
 * Method:    prepareAll
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_titikaka_mediaproxyandroid_NDKGateWay_prepareAll
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_titikaka_mediaproxyandroid_NDKGateWay
 * Method:    start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_titikaka_mediaproxyandroid_NDKGateWay_start
  (JNIEnv *, jobject);

/*
 * Class:     com_titikaka_mediaproxyandroid_NDKGateWay
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_titikaka_mediaproxyandroid_NDKGateWay_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_titikaka_mediaproxyandroid_NDKGateWay
 * Method:    cleanAll
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_titikaka_mediaproxyandroid_NDKGateWay_cleanAll
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_titikaka_mediaproxyandroid_NDKGateWay_sendCommand
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
